export const goals = [
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
    },
]
