export const goals = [
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-1.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-01.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-2.jpg',
        bgColor: '#dda73a',
        goalDesc:
            'End hunger, achieve food security and improved nutrition and promote sustainable agriculture.',
        targets: 8,
        events: 24,
        publications: 9,
        actions: 772,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-02.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-3.jpg',
        bgColor: '#4ca146',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-03.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-4.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-04.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-5.jpg',
        bgColor: 'red',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-05.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-6.jpg',
        bgColor: '#27bfe6',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-06.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-7.jpg',
        bgColor: '#fbc412',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-07.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-8.jpg',
        bgColor: '#a31c44',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-08.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-9.jpg',
        bgColor: '#f26a2d',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-09.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-10.jpg',
        bgColor: '#e01483',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-10.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-11.jpg',
        bgColor: '#f89d2a',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-11.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-12.jpg',
        bgColor: '#bf8d2c',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-12.jpg',
    },
    {
        linkTo: '/target',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-13.jpg',
        bgColor: '#407f46',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-13.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-14.jpg',
        bgColor: '#1f97d4',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-14.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-15.jpg',
        bgColor: '#59ba48',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-15.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-16.jpg',
        bgColor: '#dda73a',
        goalDesc:
            'End hunger, achieve food security and improved nutrition and promote sustainable agriculture.',
        targets: 8,
        events: 24,
        publications: 9,
        actions: 772,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-16.jpg',
    },
    {
        linkTo: '/',
        bgUrl: 'https://sdgs.un.org/themes/custom/porto/assets/goals/images/img-goal-17.jpg',
        bgColor: '#13496b',
        goalDesc: 'End poverty in all its forms everywhere.',
        targets: 7,
        events: 34,
        publications: 31,
        actions: 846,
        bottomImgUrl:
            'https://sdgs.un.org/sites/default/files/goals/E_SDG_Icons-17.jpg',
    },
]
